<?php
/**
 * Fuel
 *
 * Fuel is a fast, lightweight, community driven PHP5 framework.
 *
 * @package    Fuel
 * @version    1.0
 * @author     Fuel Development Team
 * @license    MIT License
 * @copyright  2010 - 2011 Fuel Development Team
 * @link       http://fuelphp.com
 */


Autoloader::add_core_namespace('Swift');

Autoloader::add_classes(array(
	'Swift\\Swift' => __DIR__.'/classes/swift.php',
	
	'Swift\\Swift_Attachment' => __DIR__.'/classes/swift/Attachment.php',
	'Swift\\Swift_ByteStream_AbstractFilterableInputStream' => __DIR__.'/classes/swift/ByteStream/AbstractFilterableInputStream.php',
	'Swift\\Swift_ByteStream_ArrayByteStream' => __DIR__.'/classes/swift/ByteStream/ArrayByteStream.php',
	'Swift\\Swift_ByteStream_FileByteStream' => __DIR__.'/classes/swift/ByteStream/FileByteStream.php',
	'Swift\\Swift_CharacterReader_GenericFixedWidthReader' => __DIR__.'/classes/swift/CharacterReader/GenericFixedWidthReader.php',
	'Swift\\Swift_CharacterReader_UsAsciiReader' => __DIR__.'/classes/swift/CharacterReader/UsAsciiReader.php',
	'Swift\\Swift_CharacterReader_Utf8Reader' => __DIR__.'/classes/swift/CharacterReader/Utf8Reader.php',
	'Swift\\Swift_CharacterReader' => __DIR__.'/classes/swift/CharacterReader.php',
	'Swift\\Swift_CharacterReaderFactory_SimpleCharacterReaderFactory' => __DIR__.'/classes/swift/CharacterReaderFactory/SimpleCharacterReaderFactory.php',
	'Swift\\Swift_CharacterReaderFactory' => __DIR__.'/classes/swift/CharacterReaderFactory.php',
	'Swift\\Swift_CharacterStream_ArrayCharacterStream' => __DIR__.'/classes/swift/CharacterStream/ArrayCharacterStream.php',
	'Swift\\Swift_CharacterStream_NgCharacterStream' => __DIR__.'/classes/swift/CharacterStream/NgCharacterStream.php',
	'Swift\\Swift_CharacterStream' => __DIR__.'/classes/swift/CharacterStream.php',
	'Swift\\Swift_DependencyContainer' => __DIR__.'/classes/swift/DependencyContainer.php',
	'Swift\\Swift_DependencyException' => __DIR__.'/classes/swift/DependencyException.php',
	'Swift\\Swift_EmbeddedFile' => __DIR__.'/classes/swift/EmbeddedFile.php',
	'Swift\\Swift_Encoder_Base64Encoder' => __DIR__.'/classes/swift/Encoder/Base64Encoder.php',
	'Swift\\Swift_Encoder_QpEncoder' => __DIR__.'/classes/swift/Encoder/QpEncoder.php',
	'Swift\\Swift_Encoder_Rfc2231Encoder' => __DIR__.'/classes/swift/Encoder/Rfc2231Encoder.php',
	'Swift\\Swift_Encoder' => __DIR__.'/classes/swift/Encoder.php',
	'Swift\\Swift_Encoding' => __DIR__.'/classes/swift/Encoding.php',
	'Swift\\Swift_Events_CommandEvent' => __DIR__.'/classes/swift/Events/CommandEvent.php',
	'Swift\\Swift_Events_CommandListener' => __DIR__.'/classes/swift/Events/CommandListener.php',
	'Swift\\Swift_Events_Event' => __DIR__.'/classes/swift/Events/Event.php',
	'Swift\\Swift_Events_EventDispatcher' => __DIR__.'/classes/swift/Events/EventDispatcher.php',
	'Swift\\Swift_Events_EventListener' => __DIR__.'/classes/swift/Events/EventListener.php',
	'Swift\\Swift_Events_EventObject' => __DIR__.'/classes/swift/Events/EventObject.php',
	'Swift\\Swift_Events_ResponseEvent' => __DIR__.'/classes/swift/Events/ResponseEvent.php',
	'Swift\\Swift_Events_ResponseListener' => __DIR__.'/classes/swift/Events/ResponseListener.php',
	'Swift\\Swift_Events_SendEvent' => __DIR__.'/classes/swift/Events/SendEvent.php',
	'Swift\\Swift_Events_SendListener' => __DIR__.'/classes/swift/Events/SendListener.php',
	'Swift\\Swift_Events_SimpleEventDispatcher' => __DIR__.'/classes/swift/Events/SimpleEventDispatcher.php',
	'Swift\\Swift_Events_TransportChangeEvent' => __DIR__.'/classes/swift/Events/TransportChangeEvent.php',
	'Swift\\Swift_Events_TransportChangeListener' => __DIR__.'/classes/swift/Events/TransportChangeListener.php',
	'Swift\\Swift_Events_TransportExceptionEvent' => __DIR__.'/classes/swift/Events/TransportExceptionEvent.php',
	'Swift\\Swift_Events_TransportExceptionListener' => __DIR__.'/classes/swift/Events/TransportExceptionListener.php',
	'Swift\\Swift_FailoverTransport' => __DIR__.'/classes/swift/FailoverTransport.php',
	'Swift\\Swift_FileStream' => __DIR__.'/classes/swift/FileStream.php',
	'Swift\\Swift_Filterable' => __DIR__.'/classes/swift/Filterable.php',
	'Swift\\Swift_Image' => __DIR__.'/classes/swift/Image.php',
	'Swift\\Swift_InputByteStream' => __DIR__.'/classes/swift/InputByteStream.php',
	'Swift\\Swift_IoException' => __DIR__.'/classes/swift/IoException.php',
	'Swift\\Swift_KeyCache_ArrayKeyCache' => __DIR__.'/classes/swift/KeyCache/ArrayKeyCache.php',
	'Swift\\Swift_KeyCache_DiskKeyCache' => __DIR__.'/classes/swift/KeyCache/DiskKeyCache.php',
	'Swift\\Swift_KeyCache_KeyCacheInputStream' => __DIR__.'/classes/swift/KeyCache/KeyCacheInputStream.php',
	'Swift\\Swift_KeyCache_NullKeyCache' => __DIR__.'/classes/swift/KeyCache/NullKeyCache.php',
	'Swift\\Swift_KeyCache_SimpleKeyCacheInputStream' => __DIR__.'/classes/swift/KeyCache/SimpleKeyCacheInputStream.php',
	'Swift\\Swift_KeyCache' => __DIR__.'/classes/swift/KeyCache.php',
	'Swift\\Swift_LoadBalancedTransport' => __DIR__.'/classes/swift/LoadBalancedTransport.php',
	'Swift\\Swift_Mailer_ArrayRecipientIterator' => __DIR__.'/classes/swift/Mailer/ArrayRecipientIterator.php',
	'Swift\\Swift_Mailer_RecipientIterator' => __DIR__.'/classes/swift/Mailer/RecipientIterator.php',
	'Swift\\Swift_Mailer' => __DIR__.'/classes/swift/Mailer.php',
	'Swift\\Swift_MailTransport' => __DIR__.'/classes/swift/MailTransport.php',
	'Swift\\Swift_Message' => __DIR__.'/classes/swift/Message.php',
	'Swift\\Swift_Mime_Attachment' => __DIR__.'/classes/swift/Mime/Attachment.php',
	'Swift\\Swift_Mime_CharsetObserver' => __DIR__.'/classes/swift/Mime/CharsetObserver.php',
	'Swift\\Swift_Mime_ContentEncoder_Base64ContentEncoder' => __DIR__.'/classes/swift/Mime/ContentEncoder/Base64ContentEncoder.php',
	'Swift\\Swift_Mime_ContentEncoder_PlainContentEncoder' => __DIR__.'/classes/swift/Mime/ContentEncoder/PlainContentEncoder.php',
	'Swift\\Swift_Mime_ContentEncoder_QpContentEncoder' => __DIR__.'/classes/swift/Mime/ContentEncoder/QpContentEncoder.php',
	'Swift\\Swift_Mime_ContentEncoder' => __DIR__.'/classes/swift/Mime/ContentEncoder.php',
	'Swift\\Swift_Mime_EmbeddedFile' => __DIR__.'/classes/swift/Mime/EmbeddedFile.php',
	'Swift\\Swift_Mime_EncodingObserver' => __DIR__.'/classes/swift/Mime/EncodingObserver.php',
	'Swift\\Swift_Mime_Header' => __DIR__.'/classes/swift/Mime/Header.php',
	'Swift\\Swift_Mime_HeaderEncoder_Base64HeaderEncoder' => __DIR__.'/classes/swift/Mime/HeaderEncoder/Base64HeaderEncoder.php',
	'Swift\\Swift_Mime_HeaderEncoder_QpHeaderEncoder' => __DIR__.'/classes/swift/Mime/HeaderEncoder/QpHeaderEncoder.php',
	'Swift\\Swift_Mime_HeaderEncoder' => __DIR__.'/classes/swift/Mime/HeaderEncoder.php',
	'Swift\\Swift_Mime_HeaderFactory' => __DIR__.'/classes/swift/Mime/HeaderFactory.php',
	'Swift\\Swift_Mime_Headers_AbstractHeader' => __DIR__.'/classes/swift/Mime/Headers/AbstractHeader.php',
	'Swift\\Swift_Mime_Headers_DateHeader' => __DIR__.'/classes/swift/Mime/Headers/DateHeader.php',
	'Swift\\Swift_Mime_Headers_IdentificationHeader' => __DIR__.'/classes/swift/Mime/Headers/IdentificationHeader.php',
	'Swift\\Swift_Mime_Headers_MailboxHeader' => __DIR__.'/classes/swift/Mime/Headers/MailboxHeader.php',
	'Swift\\Swift_Mime_Headers_ParameterizedHeader' => __DIR__.'/classes/swift/Mime/Headers/ParameterizedHeader.php',
	'Swift\\Swift_Mime_Headers_PathHeader' => __DIR__.'/classes/swift/Mime/Headers/PathHeader.php',
	'Swift\\Swift_Mime_Headers_UnstructuredHeader' => __DIR__.'/classes/swift/Mime/Headers/UnstructuredHeader.php',
	'Swift\\Swift_Mime_HeaderSet' => __DIR__.'/classes/swift/Mime/HeaderSet.php',
	'Swift\\Swift_Mime_Message' => __DIR__.'/classes/swift/Mime/Message.php',
	'Swift\\Swift_Mime_MimeEntity' => __DIR__.'/classes/swift/Mime/MimeEntity.php',
	'Swift\\Swift_Mime_MimePart' => __DIR__.'/classes/swift/Mime/MimePart.php',
	'Swift\\Swift_Mime_ParameterizedHeader' => __DIR__.'/classes/swift/Mime/ParameterizedHeader.php',
	'Swift\\Swift_Mime_SimpleHeaderFactory' => __DIR__.'/classes/swift/Mime/SimpleHeaderFactory.php',
	'Swift\\Swift_Mime_SimpleHeaderSet' => __DIR__.'/classes/swift/Mime/SimpleHeaderSet.php',
	'Swift\\Swift_Mime_SimpleMessage' => __DIR__.'/classes/swift/Mime/SimpleMessage.php',
	'Swift\\Swift_Mime_SimpleMimeEntity' => __DIR__.'/classes/swift/Mime/SimpleMimeEntity.php',
	'Swift\\Swift_MimePart' => __DIR__.'/classes/swift/MimePart.php',
	'Swift\\Swift_OutputByteStream' => __DIR__.'/classes/swift/OutputByteStream.php',
	'Swift\\Swift_Plugins_AntiFloodPlugin' => __DIR__.'/classes/swift/Plugins/AntiFloodPlugin.php',
	'Swift\\Swift_Plugins_BandwidthMonitorPlugin' => __DIR__.'/classes/swift/Plugins/BandwidthMonitorPlugin.php',
	'Swift\\Swift_Plugins_Decorator_Replacements' => __DIR__.'/classes/swift/Plugins/Decorator/Replacements.php',
	'Swift\\Swift_Plugins_DecoratorPlugin' => __DIR__.'/classes/swift/Plugins/DecoratorPlugin.php',
	'Swift\\Swift_Plugins_Logger' => __DIR__.'/classes/swift/Plugins/Logger.php',
	'Swift\\Swift_Plugins_LoggerPlugin' => __DIR__.'/classes/swift/Plugins/LoggerPlugin.php',
	'Swift\\Swift_Plugins_Loggers_ArrayLogger' => __DIR__.'/classes/swift/Plugins/Loggers/ArrayLogger.php',
	'Swift\\Swift_Plugins_Loggers_EchoLogger' => __DIR__.'/classes/swift/Plugins/Loggers/EchoLogger.php',
	'Swift\\Swift_Plugins_Pop_Pop3Connection' => __DIR__.'/classes/swift/Plugins/Pop/Pop3Connection.php',
	'Swift\\Swift_Plugins_Pop_Pop3Exception' => __DIR__.'/classes/swift/Plugins/Pop/Pop3Exception.php',
	'Swift\\Swift_Plugins_PopBeforeSmtpPlugin' => __DIR__.'/classes/swift/Plugins/PopBeforeSmtpPlugin.php',
	'Swift\\Swift_Plugins_Reporter' => __DIR__.'/classes/swift/Plugins/Reporter.php',
	'Swift\\Swift_Plugins_ReporterPlugin' => __DIR__.'/classes/swift/Plugins/ReporterPlugin.php',
	'Swift\\Swift_Plugins_Reporters_HitReporter' => __DIR__.'/classes/swift/Plugins/Reporters/HitReporter.php',
	'Swift\\Swift_Plugins_Reporters_HtmlReporter' => __DIR__.'/classes/swift/Plugins/Reporters/HtmlReporter.php',
	'Swift\\Swift_Plugins_Sleeper' => __DIR__.'/classes/swift/Plugins/Sleeper.php',
	'Swift\\Swift_Plugins_ThrottlerPlugin' => __DIR__.'/classes/swift/Plugins/ThrottlerPlugin.php',
	'Swift\\Swift_Plugins_Timer' => __DIR__.'/classes/swift/Plugins/Timer.php',
	'Swift\\Swift_Preferences' => __DIR__.'/classes/swift/Preferences.php',
	'Swift\\Swift_ReplacementFilterFactory' => __DIR__.'/classes/swift/ReplacementFilterFactory.php',
	'Swift\\Swift_RfcComplianceException' => __DIR__.'/classes/swift/RfcComplianceException.php',
	'Swift\\Swift_SendmailTransport' => __DIR__.'/classes/swift/SendmailTransport.php',
	'Swift\\Swift_SmtpTransport' => __DIR__.'/classes/swift/SmtpTransport.php',
	'Swift\\Swift_StreamFilter' => __DIR__.'/classes/swift/StreamFilter.php',
	'Swift\\Swift_StreamFilters_ByteArrayReplacementFilter' => __DIR__.'/classes/swift/StreamFilters/ByteArrayReplacementFilter.php',
	'Swift\\Swift_StreamFilters_StringReplacementFilter' => __DIR__.'/classes/swift/StreamFilters/StringReplacementFilter.php',
	'Swift\\Swift_StreamFilters_StringReplacementFilterFactory' => __DIR__.'/classes/swift/StreamFilters/StringReplacementFilterFactory.php',
	'Swift\\Swift_SwiftException' => __DIR__.'/classes/swift/SwiftException.php',
	'Swift\\Swift_Transport_AbstractSmtpTransport' => __DIR__.'/classes/swift/Transport/AbstractSmtpTransport.php',
	'Swift\\Swift_Transport_Esmtp_Auth_CramMd5Authenticator' => __DIR__.'/classes/swift/Transport/Esmtp/Auth/CramMd5Authenticator.php',
	'Swift\\Swift_Transport_Esmtp_Auth_LoginAuthenticator' => __DIR__.'/classes/swift/Transport/Esmtp/Auth/LoginAuthenticator.php',
	'Swift\\Swift_Transport_Esmtp_Auth_PlainAuthenticator' => __DIR__.'/classes/swift/Transport/Esmtp/Auth/PlainAuthenticator.php',
	'Swift\\Swift_Transport_Esmtp_Authenticator' => __DIR__.'/classes/swift/Transport/Esmtp/Authenticator.php',
	'Swift\\Swift_Transport_Esmtp_AuthHandler' => __DIR__.'/classes/swift/Transport/Esmtp/AuthHandler.php',
	'Swift\\Swift_Transport_EsmtpHandler' => __DIR__.'/classes/swift/Transport/EsmtpHandler.php',
	'Swift\\Swift_Transport_EsmtpTransport' => __DIR__.'/classes/swift/Transport/EsmtpTransport.php',
	'Swift\\Swift_Transport_FailoverTransport' => __DIR__.'/classes/swift/Transport/FailoverTransport.php',
	'Swift\\Swift_Transport_IoBuffer' => __DIR__.'/classes/swift/Transport/IoBuffer.php',
	'Swift\\Swift_Transport_LoadBalancedTransport' => __DIR__.'/classes/swift/Transport/LoadBalancedTransport.php',
	'Swift\\Swift_Transport_MailInvoker' => __DIR__.'/classes/swift/Transport/MailInvoker.php',
	'Swift\\Swift_Transport_MailTransport' => __DIR__.'/classes/swift/Transport/MailTransport.php',
	'Swift\\Swift_Transport_SendmailTransport' => __DIR__.'/classes/swift/Transport/SendmailTransport.php',
	'Swift\\Swift_Transport_SimpleMailInvoker' => __DIR__.'/classes/swift/Transport/SimpleMailInvoker.php',
	'Swift\\Swift_Transport_SmtpAgent' => __DIR__.'/classes/swift/Transport/SmtpAgent.php',
	'Swift\\Swift_Transport_StreamBuffer' => __DIR__.'/classes/swift/Transport/StreamBuffer.php',
	'Swift\\Swift_Transport' => __DIR__.'/classes/swift/Transport.php',
	'Swift\\Swift_TransportException' => __DIR__.'/classes/swift/TransportException.php',

));

/**
 * Initialize SwiftMailer
 */
Swift::init();


/* End of file bootstrap.php */